# Generated by Django 3.2.7 on 2023-03-29 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_topic_service_host_message_service_topic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['-updated', '-created']},
        ),
    ]
