# Generated by Django 4.1.7 on 2023-03-29 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_service_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='room',
            new_name='service',
        ),
    ]
