# Generated by Django 3.2.7 on 2023-05-03 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('base', '0006_customuser_service_address_delete_adresse'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
