# Generated by Django 4.1.7 on 2023-05-10 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_delete_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='montant',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
