# Generated by Django 4.1.7 on 2023-05-10 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_service_montant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='montant',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=6),
        ),
    ]
