# Generated by Django 4.2.1 on 2023-05-23 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_service_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(default='images\\Logo_SRAD.png', upload_to='base/files/images'),
        ),
    ]
